[package]
name = "wad3parser"
version = "0.1.0"
authors = ["Robert Mikhayelyan <rob.mikh@outlook.com>"]
edition = "2021"

[dependencies]
serde = { version="1.0.140", features = ["derive"] }
bincode = "1.3.3"
byteorder = "1.4.3"
image = "0.23.12"

[dev-dependencies]
glob = "0.3.0"