[package]
name = "wad3parser"
version = "0.1.0"
authors = ["Robert Mikhayelyan <rob.mikh@outlook.com>"]
edition = "2018"

[dependencies]
serde = { version="1.0.92", features = ["derive"] }
bincode = "1.1.4"
byteorder = "1.3.1"
image = "0.23.12"

[dev-dependencies]
glob = "0.3.0"