[package]
name = "goldsrc-asset-viewer"
version = "0.1.0"
authors = ["Robert Mikhayelyan <rob.mikh@outlook.com>"]
edition = "2018"
build = "build/build.rs"

[dependencies]
#wad3parser = { path = "../wad3parser" }
wad3parser = { git = "https://github.com/robmikh/wad3parser.git" }
wgpu = "0.4.0"
winit = "0.19.5"
clap = "2.33.0"
nalgebra = "0.18"
nfd = "0.0.4"
image = "0.21.1"
env_logger = "0.5"
imgui = "0.2.1"
imgui-winit-support = "0.2.1"
imgui-wgpu = { git = "https://github.com/robmikh/imgui-wgpu-rs.git", branch = "update" }
mdlparser = { path = "mdlparser" }

[build-dependencies]
shaderc = "0.3"
