[package]
name = "goldsrc-asset-viewer"
version = "0.1.0"
authors = ["Robert Mikhayelyan <rob.mikh@outlook.com>"]
edition = "2018"
build = "build/build.rs"

[dependencies]
#wad3parser = { path = "../wad3parser" }
wad3parser = { git = "https://github.com/robmikh/wad3parser.git" }
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs.git" }
clap = "2.33.0"
nalgebra = "0.18"
nfd = "0.0.4"
image = "0.21.1"
env_logger = "0.5"
imgui = { git = "https://github.com/Gekkio/imgui-rs.git" }
imgui-winit-support = { git = "https://github.com/Gekkio/imgui-rs.git" }
imgui-wgpu = { git = "https://github.com/robmikh/imgui-wgpu-rs.git", branch = "master" }
mdlparser = { path = "mdlparser" }

[build-dependencies]
shaderc = "0.3"

[features]
default = []
metal = ["imgui-wgpu/metal"]
dx12 = ["imgui-wgpu/dx12"]
vulkan = ["imgui-wgpu/vulkan"]
