[package]
name = "goldsrc-asset-viewer"
version = "0.1.0"
authors = ["Robert Mikhayelyan <rob.mikh@outlook.com>"]
edition = "2021"
description = "A tool to view assets from GoldSource games."

[dependencies]
wad3parser = { path = "wad3parser" }
wgpu = "0.13.1"
winit = "0.26"
clap = { version = "3.2.15", features = ["derive"] }
glam = "0.21.2"
rfd = "0.10.0"
image = "0.23.12"
env_logger = "0.9.0"
imgui = "0.8.2"
imgui-winit-support = { version = "0.8.2", default-features = false, features = ["winit-26"] }
imgui-wgpu = "0.20.0"
pollster = "0.2.5"
mdlparser = { path = "mdlparser" }
id_tree = "1.8.0"
