[package]
name = "mdlparser"
version = "0.1.0"
authors = ["Robert Mikhayelyan <rob.mikh@outlook.com>"]
edition = "2021"

[dependencies]
serde = { version="1.0.200", features = ["derive"] }
bincode = "1.3.3"
byteorder = "1.4.3"
image = "0.23.12"

